### ISSUE TITLE
Values show up in the left pane but not inside the tabs

### ISSUE THREAD

**Issue by Emma03L** [Mechanical-Advantage/AdvantageScope#223] opened 2024-10-14 10:46 UTC
**Describe the bug**
values exist and update in the left pane but when put into tabs no value is shown next to the name or in the graph.

**To Reproduce**
I am not sure how to reproduce it but closing and reopening the application seemed to solve it.

**Expected behavior**
I expected the values to show up as graphs correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/5dee07d9-a873-453f-8e98-9e51f316c140)
![image](https://github.com/user-attachments/assets/7031711b-7d12-4571-a8e5-002f25491813)
The value `AbsoluteEncoderAngle` is present and is updating on the left (under Hood) but isn't doing anything in the graphs.

**Version (required):**
Version: 4.0.0-beta-1
Distributor: FRC 6328
Platform: win32-x64
Build Date: 9/26/2024, 24:41:47 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Comment by jwbonner** [comment] 2024-10-15 03:09
It looks like the line graph isn't rendering at all. If this occurs again, it would be helpful if you can check for errors in the developer console (go to "View" > "Toggle Developer Tools").

Without being able to recreate this, there's very little I can do to fix it.

**Comment by jwbonner** [comment] 2024-10-28 04:26
My best guess is that this is a duplicate of #238, given that the screenshots show an image of the statistics tab. If the issue is not fixed on the next beta release of AdvantageScope, feel free to reopen.

**Closed by jwbonner** 2024-10-28 04:26 UTC
Labels: bug
