### ISSUE TITLE
3D Component Poses ignore base robot model transformations.

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#279] opened 2024-11-25 22:41 UTC
In our robot's model, we have to transform the robot model up for the wheels to be above the ground. However, when logging component poses, it does not respect this offset. This means we have to add an arbitrary offset to every single component pose. It would be nice to either make it respect these transformations or allow JSON configuration of these components to respect or not respect these.

![image](https://github.com/user-attachments/assets/72d3b85e-b74a-4f40-9549-fae9c29a93d5)

**Comment by jwbonner** [comment] 2024-11-25 22:45
Component poses are always relative to the robot origin, which is defined to be on the ground. This is the standard reference frame used for everything in AdvantageScope. When following the documented setup steps, component poses can be published using that same reference frame. I'm not sure I understand what the issue is. Are you trying to use a different reference frame for publishing components?

**Comment by blaze-developer** [comment] 2024-11-25 23:13
![image](https://github.com/user-attachments/assets/770b2d2f-e459-4a8a-9c89-cfb3b6d1c80f)

This is my configuration. I am using a 0.045 meter z offset to get the wheels onto the ground.

![image](https://github.com/user-attachments/assets/d8842798-9e31-48b8-b4b0-8d7bd346c667)

My problem, is that the visualized component poses are relative to the floor, and not the offset robot pose, the components do not follow the robot with its transformations.

![image](https://github.com/user-attachments/assets/fa12e5b5-8a5c-47d3-9b3b-6748acfa4a85)

**Comment by jwbonner** [comment] 2024-12-05 16:01
The "actual origin" of the robot is on the floor, which is the default approach used by WPILib when converting between 2D and 3D poses (and is used by most teams). You're welcome to use a different system in your code, but AdvantageScope expects that components will be published using a standard coordinate system.

**Comment by jwbonner** [comment] 2024-12-06 19:52
Closing this issue for now, since this is the intended behavior for robot models. I added a note to the documentation clarifying the coordinate system for 3D components.

**Closed by jwbonner** 2024-12-06 19:52 UTC
Labels: bug

**Comment by blaze-developer** [comment] 2024-12-13 18:46
Would you recommend making the origin of robot models in CAD on the floor in future projects to find coordinates easier without offsets?

**Comment by jwbonner** [comment] 2024-12-13 18:49
The coordinate system that you choose to use in CAD and robot code is up to you, and we recommend following the setup process in the documentation for configuring the model in AdvantageScope.
