### ISSUE TITLE
AdvantageScope incorrectly decodes Struct with a Struct array field

### ISSUE THREAD

**Issue by bhall-ctre** [Mechanical-Advantage/AdvantageScope#277] opened 2024-11-25 20:53 UTC
**Describe the bug**
At least while connected to simulation, AdvantageScope incorrectly decodes a Struct where one of its fields is an array of structs, such as with `SwerveDriveKinematics`.

**To Reproduce**

1. Create a `StructPublisher<SwerveDriveKinematics>` in code, and periodically publish a `SwerveDriveKinematics` over NT.
2. Run in simulation, and connect AdvantageScope to simulation.

**Expected behavior**
The SwerveDriveKinematics object should have an array of `Translation2d modules`.
Instead, AdvantageScope reports it as a single `Translation2d`, specifically index 0.

**Screenshots**
AdvantageScope:
![image](https://github.com/user-attachments/assets/1e191d1d-6d99-47e7-b804-70e1a521c07c)
Glass:
![image](https://github.com/user-attachments/assets/30b5151c-262a-415d-a0ba-f3b03b46a1f7)

**Version (required):**

Version: 4.0.0-beta-3
Distributor: WPILib
Platform: win32-x64
Build Date: 11/12/2024, 05:10:47 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

Also tested on a more recent dev build (after https://github.com/Mechanical-Advantage/AdvantageScope/pull/274):

Version: 4.0.0-beta-3
Distributor: FRC 6328
Platform: win32-x64
Build Date: 11/19/2024, 05:02:59 UTC
Electron: 32.0.2
Chromium: 128.0.6613.84
Node: 20.16.0

**Additional context**
Some sample code is shown below.
```java
    private final StructPublisher<SwerveDriveKinematics> m_kinematicsPublisher = NetworkTableInstance.getDefault()
        .getTable("SwerveKinematics")
        .getStructTopic("State", SwerveDriveKinematics.getStruct(4))
        .publish();

    private final SwerveDriveKinematics m_kinematics = new SwerveDriveKinematics(
        new Translation2d(0.267, 0.267),
        new Translation2d(0.267, -0.267),
        new Translation2d(-0.267, 0.267),
        new Translation2d(-0.267, -0.267)
    );

    @Override
    public void robotPeriodic() {
        m_kinematicsPublisher.set(m_kinematics);
    }
```

**Comment by jwbonner** [comment] 2024-11-25 21:50
Thanks for reporting. There was an edge case where struct array fields were only being decoded for primitive types and not nested structs. The fix works as intended with your sample code, and will be in the next release.

<img width="535" alt="Screenshot 2024-11-25 at 4 49 37 PM" src="https://github.com/user-attachments/assets/e55168ea-3d57-4624-9b8c-ef2da9639b08">

**Closed by jwbonner** 2024-11-25 21:50 UTC
Labels: bug
