### ISSUE TITLE
Beta: Window and title rendering

### ISSUE THREAD

**Issue by blaze-developer** [Mechanical-Advantage/AdvantageScope#207] opened 2024-09-29 19:40 UTC
Pulling the windows version of the beta down, there have been a few issues with the window and its alt menu.

When starting up the program, for a few seconds, the minimize fullscreen and exit controls cover the other buttons inside the program.

![image](https://github.com/user-attachments/assets/0b693541-0e61-4da5-a9e4-c4c8973cbaee)

And when the program is in fullscreen, the original alt menu appears when I change sources/the window title changes.

![image](https://github.com/user-attachments/assets/e5ba0df0-8649-4a2e-b8d0-8fa87dfde7a0)

Steps:
Open on windows
Fullscreen the window
Press keybinds like CTRL+K or CTRL+SHIFT+K

**Comment by jwbonner** [comment] 2024-10-05 23:16
Both issues are now fixed. The button overlap issue was caused by the window being displayed before the DOM finished updating. The title bar issue is a duplicate of #199 (see https://github.com/Mechanical-Advantage/AdvantageScope/issues/197#issuecomment-2395222600).

**Closed by jwbonner** 2024-10-05 23:16 UTC
Labels: bug
