### ISSUE TITLE
Game piece objects

### ISSUE THREAD

**Issue by lobsterwise** [Mechanical-Advantage/AdvantageScope#135] opened 2024-01-26 15:03 UTC
It would be nice to have note game pieces as objects in the 3D view to use for visualization. Cones and cubes would be nice as well, but not required.

**Comment by jwbonner** [comment] 2024-01-26 17:08
Duplicate of #90

I definitely agree with the suggestion though.

**Closed by jwbonner** 2024-01-26 17:08 UTC
Labels: enhancement
